apiVersion: v1
kind: Namespace
metadata:
  name: geochangemllm
  labels:
    app.kubernetes.io/part-of: geochangemllm
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
