apiVersion: v1
kind: ResourceQuota
metadata:
  name: geochangemllm-quota
  namespace: geochangemllm
spec:
  hard:
    pods: "4"
    persistentvolumeclaims: "2"
    requests.cpu: "16"
    requests.memory: 64Gi
    limits.cpu: "16"
    limits.memory: 64Gi
    requests.nvidia.com/gpu: "2"
    requests.storage: 200Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: geochangemllm-limits
  namespace: geochangemllm
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "2"
        memory: 8Gi
      default:
        cpu: "8"
        memory: 32Gi
      max:
        cpu: "16"
        memory: 64Gi
